name: Continous Integration and Deployment

on:
  push:
    branches:
       - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dot Net 8 Packages
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restoring dotnet Packages
        run: dotnet restore
        
      - name: Building project
        run: dotnet build -c Release --no-restore
      
      - name: Run Automated Test
        run: dotnet test -c Release --no-build

      - name: Publish App
        run: dotnet publish -c Release -o ./out

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: cicdWindow
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE1 }} 
          package: ./out
            
      

        
        
