name: Continous Integration and Deployment

on:
  push:
    branches:
       - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dot Net 8 Packages
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restoring dotnet Packages
        run: dotnet restore
        
      - name: Building project
        run: dotnet build -c Release --no-restore
      
      - name: Run Automated Test
        run: dotnet test -c Release --no-build
      
        

        
        
